name: PullRequest

on: [ pull_request ]

jobs:
  build-objective-git:
    name: Build objective-git
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [ Xcode_12.5, Xcode_13.1, Xcode_13.2.1, Xcode_13.0, Xcode_12.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: pre build
        run: script/bootstrap && script/update_libgit2
      - name: Test and archive project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test archive ARCHS="x86_64 arm64"
